// <auto-generated />
using System;
using Artha.Backend.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Artha.Backend.Persistence.Migrations
{
    [DbContext(typeof(ArthaDbContext))]
    [Migration("20250621035941_AddedTradeableEtfEntity")]
    partial class AddedTradeableEtfEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Artha.Backend.Domain.Entity.TradeableEtfEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Exchange")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("ID");

                    b.HasIndex("Symbol", "Exchange")
                        .IsUnique();

                    b.ToTable("TradeableEtfs");
                });

            modelBuilder.Entity("Artha.Backend.Domain.Entity.ZerodhaConfig", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("APIKey")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("PublicToken")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Secret")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("ID");

                    b.HasIndex("ID")
                        .IsUnique();

                    b.ToTable("ZerodhaConfig");
                });

            modelBuilder.Entity("Artha.Backend.Domain.Entity.ZerodhaHoldingsEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("authorised_date")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("authorised_quantity")
                        .HasColumnType("int");

                    b.Property<decimal?>("average_price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("close_price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("collateral_quantity")
                        .HasColumnType("int");

                    b.Property<string>("collateral_type")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<float?>("day_change")
                        .HasColumnType("real");

                    b.Property<float?>("day_change_percentage")
                        .HasColumnType("real");

                    b.Property<bool?>("discrepancy")
                        .HasColumnType("bit");

                    b.Property<string>("exchange")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("instrument_token")
                        .HasColumnType("int");

                    b.Property<string>("isin")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("last_price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("opening_quantity")
                        .HasColumnType("int");

                    b.Property<float?>("pnl")
                        .HasColumnType("real");

                    b.Property<decimal?>("price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("product")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("quantity")
                        .HasColumnType("int");

                    b.Property<int?>("realised_quantity")
                        .HasColumnType("int");

                    b.Property<int?>("t1_quantity")
                        .HasColumnType("int");

                    b.Property<string>("tradingsymbol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("used_quantity")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("tradingsymbol", "exchange")
                        .IsUnique();

                    b.ToTable("ZerodhaHoldings");
                });

            modelBuilder.Entity("Artha.Backend.Domain.Entity.ZerodhaTradeableInstrumentEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("exchange")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("exchange_token")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("expiry")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("instrument_token")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("instrument_type")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<decimal?>("last_price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("lot_size")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("segment")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("strike")
                        .HasColumnType("decimal(18,2)");

                    b.Property<float?>("tick_size")
                        .HasColumnType("real");

                    b.Property<string>("tradingsymbol")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("ID");

                    b.HasIndex("exchange", "tradingsymbol")
                        .IsUnique();

                    b.ToTable("ZerodhaTradeableInstruments");
                });
#pragma warning restore 612, 618
        }
    }
}
