<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CsvHelper" Version="33.1.0" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="8.0.1" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.2" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Tech.Zerodha.KiteConnect" Version="4.3.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Artha.Backend.Domain.Entity\Artha.Backend.Domain.Entity.csproj" />
    <ProjectReference Include="..\Artha.Backend.Shared.Dto\Artha.Backend.Shared.Dto.csproj" />
    <ProjectReference Include="..\Artha.Backend.Domain.Contract\Artha.Backend.Domain.Contract.csproj" />
  </ItemGroup>

</Project>
